
package wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CountryImpl", targetNamespace = "http://ws.mahtabalam.net/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CountryImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInterestingFacts", targetNamespace = "http://ws.mahtabalam.net/", className = "wsclient.GetInterestingFacts")
    @ResponseWrapper(localName = "getInterestingFactsResponse", targetNamespace = "http://ws.mahtabalam.net/", className = "wsclient.GetInterestingFactsResponse")
    @Action(input = "http://ws.mahtabalam.net/CountryImpl/getInterestingFactsRequest", output = "http://ws.mahtabalam.net/CountryImpl/getInterestingFactsResponse")
    public String getInterestingFacts(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCapital", targetNamespace = "http://ws.mahtabalam.net/", className = "wsclient.GetCapital")
    @ResponseWrapper(localName = "getCapitalResponse", targetNamespace = "http://ws.mahtabalam.net/", className = "wsclient.GetCapitalResponse")
    @Action(input = "http://ws.mahtabalam.net/CountryImpl/getCapitalRequest", output = "http://ws.mahtabalam.net/CountryImpl/getCapitalResponse")
    public String getCapital(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLanguages", targetNamespace = "http://ws.mahtabalam.net/", className = "wsclient.GetLanguages")
    @ResponseWrapper(localName = "getLanguagesResponse", targetNamespace = "http://ws.mahtabalam.net/", className = "wsclient.GetLanguagesResponse")
    @Action(input = "http://ws.mahtabalam.net/CountryImpl/getLanguagesRequest", output = "http://ws.mahtabalam.net/CountryImpl/getLanguagesResponse")
    public String getLanguages(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAirports", targetNamespace = "http://ws.mahtabalam.net/", className = "wsclient.GetAirports")
    @ResponseWrapper(localName = "getAirportsResponse", targetNamespace = "http://ws.mahtabalam.net/", className = "wsclient.GetAirportsResponse")
    @Action(input = "http://ws.mahtabalam.net/CountryImpl/getAirportsRequest", output = "http://ws.mahtabalam.net/CountryImpl/getAirportsResponse")
    public String getAirports(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDistricts", targetNamespace = "http://ws.mahtabalam.net/", className = "wsclient.GetDistricts")
    @ResponseWrapper(localName = "getDistrictsResponse", targetNamespace = "http://ws.mahtabalam.net/", className = "wsclient.GetDistrictsResponse")
    @Action(input = "http://ws.mahtabalam.net/CountryImpl/getDistrictsRequest", output = "http://ws.mahtabalam.net/CountryImpl/getDistrictsResponse")
    public int getDistricts(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPlacesToVisit", targetNamespace = "http://ws.mahtabalam.net/", className = "wsclient.GetPlacesToVisit")
    @ResponseWrapper(localName = "getPlacesToVisitResponse", targetNamespace = "http://ws.mahtabalam.net/", className = "wsclient.GetPlacesToVisitResponse")
    @Action(input = "http://ws.mahtabalam.net/CountryImpl/getPlacesToVisitRequest", output = "http://ws.mahtabalam.net/CountryImpl/getPlacesToVisitResponse")
    public String getPlacesToVisit(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
